### ISSUE TITLE
Docs and model don't match

### ISSUE THREAD

**Issue by jd-lara** [cuihantao/andes#85] opened 2020-07-29 22:54 UTC
The equation for `delta0` seems not to match the result from running the line `print(ss.GENROU.doc())`

![image](https://user-images.githubusercontent.com/16385323/88861766-82153300-d1b3-11ea-94cd-878e614d54bc.png)

![image](https://user-images.githubusercontent.com/16385323/88861810-9fe29800-d1b3-11ea-9ee7-b27e13f29813.png)

**Comment by cuihantao** [comment] 2020-07-29 22:59
They look different because the Latex equations use the pretty symbols. If you look up the symbol of each variable of the command line `delta0` and substitute each with the symbol, you should fine them match. Internally, this substitution is done by SymPy.

**Comment by jd-lara** [comment] 2020-07-29 23:02
But the equations in the docs substracts `theta` in the denominator of the `atan` and in the autogenerated docs it shows the term `_a` which is different.

**Comment by cuihantao** [comment] 2020-07-29 23:08
Ah, I see you point. Something weird might be there assigning the symbols or substitution. 

The equations from `doc()` are the equations for simulation and should be correct.

**Comment by cuihantao** [comment] 2020-07-30 00:24
This issue is caused by an unintended chained substitution. 

`_a` got substituted by its symbol, `a`, which happen to be the voltage phase angle variable. `a` then got substituted by `r'\theta`.

Changed the `tex_name`s of `_a` and `_b` to `a'` and `b'`, respectively. I will need to avoid assigning existing variable names as the `tex_name` of others.

Fixed in ee549ca

Use the `latest` branch of the documentation:
https://andes.readthedocs.io/en/latest/groupdoc/SynGen.html#genrou

**Closed** 2020-08-01 00:20 UTC
